module.exports = [
    'fjernbetjening',
    'gule smukke sommerfugle',
    'skildpadde',
    'paraply',
    'lysestage',
    'vilde heste løber',
    'højttaler',
    'regnbue',
    'bibliotek',
    'ny begyndelse',
    'gammel ven',
    'skattejagt',
    'klippeklatring',
    'discord',
    'duckydk',
    'kaffemaskine',
    'smukke gamle bygninger',
    'kærlighed',
    'helikopter',
    'eventyrland',
    'røde lamper',
    'drømmefanger',
    'du dyfter af skinke',
    'hemmelighed',
    'labyrint',
    'lang rejse',
    'minecraft',
    'hunden gøer i gården',
    'tordenvejr',
    'eksplosion',
    'jeg er gammel og rynket',
    'tror du skal have briller',
    'mississippi',
    'campingvogn',
    'mikroovn',
    'katten jagter en mus',
    'mindeværdig',
    'dekorationer',
    'Underholdning',
    'min kontorstol er brun',
    'danmark',
    'mælkevejen',
    'lasse vestergaard',
    'grønne marker vokser',
    'kølige regndråber falder',
    'mørket falder over byen',
    'fuglene flyver over træerne',
    'skoene står ved døren',
    'kig bag ved dig',
    'vindet det står åbent',
    'lyset tændes i rummet',
    'bogen ligger på bordet',
    'håber du kan gætte det her ord',
    'youtube',
    'mandens avis er våd'
];